import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ContextProvider from "@/context";
import { cookieToInitialState } from "wagmi";
import { wagmiConfig } from "@/config";
import { headers } from "next/headers";
import Navbar from "./_navbar";
import Footer from "./_footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const initialState = cookieToInitialState(
    wagmiConfig,
    (await headers()).get('cookie')
  )

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center justify-between h-screen p-0`}
      >
        <ContextProvider initialState={initialState}>
          <Navbar/>
            {children}
          <Footer/>
        </ContextProvider>
      </body>
    </html>
  );
}
